import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./(components)/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen relative p-0.5 bg-green-500 text-black">
          <SideNav />
          <div className="flex relative ml-0.5 justify-center w-full rounded bg-slate-200">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
